### ISSUE TITLE
Implement memory for account login

### ISSUE THREAD

**Issue by SpencerKersey** [CSC510-Team-57/ShopSync-SE_P3#2]
At the moment, when you refresh the webpage, you are logged out of your account. It would be nice for a type of tokenization memory to be used to remember if you are logged in and have it expire after a certain amount of time.

**Comment by Charlie-Eastin** [comment]
This appears to be fixed now, should I go ahead and close it?

**Comment by SpencerKersey** [comment]
Yeah, I think everything is functional now
